### ISSUE TITLE
Typo or error in RecordSection docs

### ISSUE THREAD

**Issue by pusateri** [NLnetLabs/domain-core#3]
Looking at the docs page in doc/domain_core/bits/message/struct.RecordSection.html and found some issues. ParseRecord probably should be ParsedRecord and into_record() doesn't seem to link anywhere.

**Comment by partim** [comment]
Seems that part of the documentation needs some love, indeed!

**Comment by partim** [comment]
I hope the modified documentation is better.

One note, though: `RecordSection` itself actually does iterate over `ParsedRecord`. It only starts producing records once you trade it in via the `limit_to` method.
